title: 'food for thought'
tagline: spawn(programming, apply, [for_fun, for_profit])
author:
    name: Moritz
    email: moritz@tibidat.com
    github_url: https://github.com/m2w
    twitter_url: https://twitter.com/tibidat
    google_plus_url: https://plus.google.com/u/0/113461142832340811357/

dedicated-pages:
    - details:
        title: About
        url: /about.html
    - details:
        title: Readinglist
        url: /readinglist.html

# config
permalink: /:year/:month/:day/:title
exclude: ["CNAME", "config.rb", "talaria", "Rakefile"]
markdown: redcarpet
paginate: 2
server_port: 8001
pygments: true
