title: 'food for thought'
tagline: "Hi I'm <a href='/about.html'>Moritz</a>.<br> This is where I blog on programming, travel and photography."

tagcloud:
    post_limit: 5

author:
    name: Moritz
    email: moritz@tibidat.com
    github_url: https://github.com/m2w
    twitter_url: https://twitter.com/tibidat
    google_plus_url: https://plus.google.com/u/0/113461142832340811357/

# config
permalink: /:year/:month/:day/:title
exclude: ["CNAME", "config.rb", "talaria", "Rakefile"]
markdown: kramdown
paginate: 2
server_port: 8001
pygments: true
