title: 'food for thought'
tagline: "Hi, I'm <a href='/about.html'>Moritz</a>.<br> This is where I blog about programming, travel and photography."

tagcloud:
    post_limit: 5

author:
    name: Moritz
    email: moritz@tibidat.com
    github: https://github.com/m2w
    flickr: http://flickr.com/photos/tibidat/

# config
permalink: /:year/:month/:day/:title
exclude: ["CNAME", "config.rb", "Rakefile"]
markdown: kramdown
paginate: 2
paginate_path: ":num"
port: 8001
pygments: true
